name: 앗코의 개발일기
title: 앗코의 개발일기
email: me@atko.space
lang: ko
description: >-
  사회에 갓 입성한 개발자가 살면서 겪은 개발일을 적어내려가는 공간입니다.

resource: "/assets/res"

baseurl: ""
url: "https://blog.atko.space"
github_username: atkodev

date_format: "%B %-d, %Y"

sass:
  sass_dir: _scss

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 6

exclude: [vendor]
highlighter: rouge
kramdown:
  input: GFM
paginate_path: "/page-:num/"
permalink: pretty
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      excerpt_separator: "<!--more-->"